### ISSUE TITLE
viacep

### ISSUE THREAD

**Issue by paulobreim** [Leocardoso94/cep_future#9]
sugiro retirar o viacep porque ele está desatualizado.

melhor usar apenas a **base oficial** e trazer a informação correta. Ainda que se pense em usar o viacep como alternativo, caso o correio esteja fora do ar (o que é improvável) de nada adianta trazer u nome de rua que está incorreto.

**Comment by LucasSnatiago** [comment]
Dê uma olhada nessa issue: #12

**Comment by paulobreim** [comment]
resolvido com uso de outra lib
